"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Still.py']
DATA_FILES = ['siteslist']
OPTIONS = {
    'argv_emulation': False,
    'iconfile': 'still_icon.icns'
    #  sips -s format icns still_icon.png --out still_icon.icns
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

# to run setup: python3 setup.py py2app
